# matrix:
#   include:
#     # works on Precise and Trusty
#     - os: linux
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-5
#       env:
#          - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
#     - os: osx
#       osx_image: xcode8
#       env:
#         - MATRIX_EVAL="brew install gcc && CC=gcc-6 && CXX=g++-6"

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

# before_install:
#     - eval "${MATRIX_EVAL}"

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && make test
